apiVersion: v1
kind: Service
metadata:
  name: image-micro-service
  namespace: human-connection
  labels:
    human-connection.org/selector: deployment-human-connection-image-micro-service
spec:
  ports:
    - name: web
      port: 4000
      targetPort: 4000
  selector:
    human-connection.org/selector: deployment-human-connection-image-micro-service
